# Site settings
title: FTC Sim
description: >-
  A tutorial for constructing an agent-based pandemic simulation in JavaScript.

# Build settings
markdown: kramdown
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
